### PR TITLE
Support prototyped arrays

### PR DESCRIPTION
**Pull request by rami-prilutsky**
now with fixed jslint

### CODE REVIEW

**Comment by jsachs** [comment]
Why make the change to `forEach` in the converter, but check for a `function` type in the other files? The `forEach` reads easier.

Also, could you add tests for your changes to keep the code coverage up?

**Comment by rami-prilutsky** [comment]
I've added the `forEach` where I was certain it's an array, in other places I wasn't.

I'll add tests.
Thanks.

**Comment by rami-prilutsky** [comment]
added, can u please merge?

**Comment by kachok** [comment]
@rami-prilutsky in leu of formal Contributor Agreement (like this https://www.apache.org/licenses/icla.txt), please comment with :+1: if you agree to donate your patch so we can continue distributing it under Apache 2.0 license.

@jsachs please merge once it's done

**Comment by rami-prilutsky** [comment]
:+1:

**Comment by rami-prilutsky** [comment]
Hi, can u update npm repo?

**Comment by jsachs** [comment]
`blue-button-cms@1.5.1-beta.1` has been published.

**Pull request merged**
